# --[ AUTOMATON ]--
fix_trend: true
fixed_quantity: true
currencies:
  - [EURUSD_ZERO, 5000]
  - [USDJPY_ZERO, 5000]
  - [USDCHF_ZERO, 5000]
  - [GBPUSD_ZERO, 5000]
  - [USDCAD_ZERO, 5000]
sleep_transactions: 86400
timeframe: 1d
count: 5

# [ PRESERVER ]
preserver:
  funds_risk: 0.5

# [ CHECKER ]
checkers:
  activate: [totalfixed, fixed]
  totalfixed:
    sleep: 60
    gain: 35  # 35 * 1.8
    loss: null
  totalrelative:
    sleep: 60
    gain: 12  # 35 / 5
    loss: null
  fixed:
    sleep: 60
    gain: null
    loss: 40
  # relative:
  #   sleep: 600
  #   gain: 0.005
  #   loss: 0.005
  #   avg:
  #     timeframe: 1h
  #     count: 5
  # reversion:
  #   sleep: 60
  #   timeframe: 1h
