# --[ AUTOMATON ]--
fix_trend:          true
fixed_quantity:     true
currencies:
  - [AUDUSD, 5000, 0]
  - [EURCHF, 5000, 0]
  - [EURGBP, 5000, 0]
  - [EURRUB, 2000, 1]
  - [EURJPY, 5000, 0]
  - [EURUSD, 5000, 0]
  - [GBPUSD, 6000, 0]
  - [USDCAD, 5000, 0]
  - [USDCHF, 5000, 0]
  - [USDRUB, 2000, 1]
  - [USDJPY, 5000, 0]
sleep_transactions: 86400
timeframe: 1d
count: 5
