# --[ AUTOMATON ]--
fix_trend:          true
fixed_quantity:     true
currencies:
  - [AUDUSD, 5000, 0]
  - [EURCHF, 5000, 0]
  - [EURGBP, 5000, 0]
  - [EURRUB, 2000, 1]
  - [EURJPY, 5000, 0]
  - [EURUSD, 5000, 0]
  - [GBPUSD, 6000, 0]
  - [USDCAD, 5000, 0]
  - [USDCHF, 5000, 0]
  - [USDRUB, 2000, 1]
  - [USDJPY, 5000, 0]
sleep_transactions: 86400
timeframe: 1d
count: 5

# [ PRESERVER ]
preserver:
  allow_high_risk:  false
  funds_risk: 0.5
  concurrent_movements: 5

# [ CHECKER ]
checkers:
  activate: [totalfixed, fixed]
  totalfixed:
    sleep: 60
    gain: 35  # 35 * 1
    loss: null
  totalrelative:
    sleep: 60
    gain: 12  # 35 / 5
    loss: null
  fixed:
    sleep: 60
    gain: null
    loss: 40
  # relative:
  #   sleep: 600
  #   gain: 0.005
  #   loss: 0.005
  #   avg:
  #     timeframe: 1h
  #     count: 5
  # reversion:
  #   sleep: 60
  #   timeframe: 1h
