# --[ AUTOMATON ]--
fix_trend: true
# fixed margin to use
margin_to_use: 125
currencies:
  - [AUDUSD, 1000, 0]
  - [EURCHF, 1000, 0]
  - [EURGBP, 1000, 0]
  - [EURRUB, 1000, 1]
  - [EURJPY, 1000, 0]
  - [EURUSD, 1000, 0]
  - [GBPUSD, 1000, 0]
  - [USDCAD, 1000, 0]
  - [USDCHF, 1000, 0]
  - [USDRUB, 1000, 1]
  - [USDJPY, 1000, 0]
sleep_transactions: 3600
timeframe: 1d
count: 1000
